/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package excepciones;

import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;

/**
 *
 * @author xaldo
 */
public class Excepciones {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
		try {
		String nombre = br.readLine();
		int div = 8/0;
		} catch (IOException e) {
			//TODO AUTOGENERATED CATCH BLOCK
			e.printStackTrace();
		}catch (ArithmeticException es) {
			//TODO AUTOGENERATED CATCH BLOCK
			System.out.println("NO PUEDE DIVIDIR PARA CERO");
		}
		
    }
    
}
